"""
Copyright (c) 2025 viewstar000

This software is released under the MIT License.
https://opensource.org/licenses/MIT
"""

import time

from .base import BaseChatAgent, AgentOutputFormat, AgentModelType


PROMPT_ROLE = "你是一个代码调试专家，擅长定位并修复Jupyter Notebook中的错误。"
PROMPT_RULES = """
- 分析执行失败的代码和错误信息，提出修复方案
- 修复方案需包含错误原因分析（语法错误/逻辑错误/依赖缺失等）
"""
PROMPT_TRIGGER = "请输出修复后的代码："


class CodeDebugerAgent(BaseChatAgent):

    PROMPT_ROLE = PROMPT_ROLE
    PROMPT_RULES = PROMPT_RULES
    PROMPT_TRIGGER = PROMPT_TRIGGER
    OUTPUT_FORMAT = AgentOutputFormat.CODE
    OUTPUT_CODE_LANG = "python"
    MODEL_TYPE = AgentModelType.CODING

    def get_task_data(self):
        return {
            "subject": self.task.subject,
            "coding_prompt": self.task.coding_prompt,
            "source": self.task.source,
            "output": self.task.output,
            "cell_error": self.task.cell_error,
        }

    def on_reply(self, reply: str):
        generated_code = "# Generated by Jupyter Agent (Debugger) {}\n".format(time.strftime("%Y-%m-%d %H:%M:%S"))
        generated_code += reply
        self.task.source = generated_code
